version: '3'

 services:

  database1:
    image: mysql
    environment : 
      - MYSQL_ROOT_PASSWORD=pucsd

    ports:
       - "3307:3306"

  database2:
    image: mysql
    environment : 
      - MYSQL_ROOT_PASSWORD=pucsd

    ports:
       - "3308:3306"
    depends_on:
       - database1


  databases3:
    image: mysql
    environment : 
      - MYSQL_ROOT_PASSWORD=pucsd

    ports:
       - "3309:3306"
    depends_on:
       - database1
